### ISSUE TITLE
Build Failure - Test failures

### ISSUE THREAD

**Issue by moooji** [kbastani/graphify#11]
Hi,
I tried to build the plugin, but got stuck with a build error because of failed test. Any ideas what could be wrong?

root@neo:/home/graphify/src/extension# mvn assembly:assembly -DdescriptorId=jar-with-dependencies
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for org.neo4j.nlp:graphify:jar:1.0.0
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-compiler-plugin is missing. @ line 113, column 21
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO]  
[INFO] ------------------------------------------------------------------------
[INFO] Building graphify 1.0.0
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] >>> maven-assembly-plugin:2.2-beta-5:assembly (default-cli) @ graphify >>>
[WARNING] The POM for org.neo4j:neo4j-cypher-commons:jar:2.1.3 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[WARNING] The POM for org.neo4j:neo4j-cypher-compiler-1.9:jar:2.0.3 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[WARNING] The POM for org.neo4j:neo4j-cypher-compiler-2.0:jar:2.0.3 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[WARNING] The POM for org.neo4j:neo4j-cypher-compiler-2.1:jar:2.1.3 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[WARNING] The POM for com.googlecode.concurrentlinkedhashmap:concurrentlinkedhashmap-lru:jar:1.3.1 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[WARNING] The POM for org.scala-lang:scala-library:jar:2.10.4 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[WARNING] The POM for org.eclipse.jetty:jetty-server:jar:9.0.5.v20130815 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[WARNING] The POM for org.eclipse.jetty:jetty-webapp:jar:9.0.5.v20130815 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[INFO] 
[INFO] --- maven-resources-plugin:2.3:resources (default-resources) @ graphify ---
[WARNING] Using platform encoding (ANSI_X3.4-1968 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /home/graphify/src/extension/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:2.0.2:compile (default-compile) @ graphify ---
[INFO] Compiling 16 source files to /home/graphify/src/extension/target/classes
[INFO] 
[INFO] --- maven-resources-plugin:2.3:testResources (default-testResources) @ graphify ---
[WARNING] Using platform encoding (ANSI_X3.4-1968 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /home/graphify/src/extension/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:2.0.2:testCompile (default-testCompile) @ graphify ---
[INFO] Compiling 2 source files to /home/graphify/src/extension/target/test-classes
[INFO] 
[INFO] --- maven-surefire-plugin:2.10:test (default-test) @ graphify ---
[INFO] Surefire report directory: /home/graphify/src/extension/target/surefire-reports

---
##  T E S T S

Running org.neo4j.nlp.impl.manager.NodeManagerTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.809 sec
Running org.neo4j.nlp.impl.util.GraphManagerTest
{0} is known {1}
Tests run: 6, Failures: 0, Errors: 3, Skipped: 0, Time elapsed: 3 sec <<< FAILURE!

Results :

Tests in error: 
  testBackwardsPropagation(org.neo4j.nlp.impl.util.GraphManagerTest): org/parboiled/scala/Parser
  testLearningManager(org.neo4j.nlp.impl.util.GraphManagerTest): org/neo4j/cypher/internal/compiler/v2_1/parser/CypherParser
  testCypherJsonResult(org.neo4j.nlp.impl.util.GraphManagerTest): org/neo4j/cypher/internal/compiler/v2_1/parser/CypherParser

Tests run: 8, Failures: 0, Errors: 3, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 21.142s
[INFO] Finished at: Thu Sep 11 15:51:27 EDT 2014
[INFO] Final Memory: 30M/72M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.10:test (default-test) on project graphify: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/graphify/src/extension/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by pedrodavidept** [comment]
I cloned this repo and built the extension with: mvn assembly:assembly -DdescriptorId=jar-with-dependencies

I'm using Neo4j v2.3.8 and 
java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)

When starting Neo4J, I got this error:

Starting Neo4j failed: org/neo4j/nlp/ext/PatternRecognitionResource : Unsupported major.minor version 52.0

@cicero19 and @moooji, How do you solve this?
